# ACCOUNT-REF-TYPE
PREVIOUS_CONTENT = "PreviousContent"
SUBSEQUENT_CONTENT = "SubsequentContent"
SUPPLEMENTAL = "Supplemental"
SEE_ALSO = "SeeAlso"
SEE_INSTEAD = "SeeInstead"

# EOL-TYPE
CR = "CR"
LF = "LF"
CRLF = "CRLF"

# HASH-FUNCTION-=TYPE
MD5 = "MD5"
SHA1 = "SHA1"
SHA224 = "SHA224"
SHA256 = "SHA256"
SHA384 = "SHA384"
SHA512 = "SHA512"
RIPEMD160 = "RIPEMD160"
WHIRLPOOL = "WHIRLPOOL"

# MESSAGE-STATUS-FLAG
SEEN = "Seen"
ANSWERED = "Answered"
FLAGGED = "Flagged"
DELETED = "Deleted"
DRAFT = "Draft"
RECENT = "Recent"