version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    ports:
    - 5601:5601
    environment:
      SERVER_NAME: tomes.kibnana.nc.gov
      ELASTICSEARCH_URL: http://192.168.99.100:9200