version: '3'

services:
  main-client:
    build: ../Services/convert_client
    volumes:
    - /mnt/data:/home/tomes/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    ports:
    - 80:80
    depends_on:
    - pst-server
    - darcmail-server
    - ner-server
    - corenlp-server
    links:
    - pst-server
    - darcmail-server
    - ner-server
    - corenlp-server
    environment:
    - TOMES_HOME=/mnt/data
  pst-server:
    build: ../Servers/pst_server
    volumes:
    - /mnt/data:/home/tomes/data
    ports:
    - 9000:9000
    environment:
    - TOMES_HOME=/mnt/data
  darcmail-server:
    build: ../Servers/darcm_server
    volumes:
    - /mnt/data:/home/tomes/data
    ports:
    - 9001:9001
    environment:
    - TOMES_HOME=/mnt/data
  ner-server:
    build: ../Servers/tomes_server
    volumes:
    - /mnt/data:/home/tomes/data
    ports:
    - 9002:9002
    environment:
    - TOMES_HOME=/mnt/data
  corenlp-server:
    build: ../Servers/corenlp_server
    ports:
    - 9003:9003
    environment:
    - TOMES_HOME=/mnt/data
